def drawtree():
    print("               *               ")
    print("              ***              ")
    print("             *****             ")
    print("            *******            ")
    print("           *********           ")
    print("          ***********          ")
    print("         *************         ")
    print("        ***************        ")
    print("       *****************       ")
    print("      *******************      ")
    print("     *********************     ")
    print("    ***********************    ")
    print("               *               ")
    print("               *               ")
    print("               *               ")
    print("               *               ")

drawtree()